### ISSUE TITLE
TypeError: a bytes-like object is required, not 'FakeMmap'

### ISSUE THREAD

**Issue by MisterB92** [martibosch/detectree#1]
When I try to run the Baseline notebook I get this error when computing the responses from LIDAR data:

"TypeError: a bytes-like object is required, not 'FakeMmap'"

I think this might have something to do using .laz files instead of .las since I had the same issue with running the example notebook from [pycrown](https://github.com/manaakiwhenua/pycrown). There I encountered the same issue but I could solve it by changing the .laz file to .las with LASzip. However using .Laz files seems to be embedded in the code for detectree. 

im using:
Ubuntu 18.04.3 LTS and jupyter notebook with anaconda 2019.10 

Looking forward to an answer

```
lidar_gdf = gpd.read_file('data/raw/lidar/lidar2014.shp')

response_dir = 'data/interim/baseline_responses'
if not path.exists(response_dir):
    os.mkdir(response_dir)
    
response_filepaths = []
for train_filepath in train_filepaths:
    response_filepath = make_response_tiles.make_response_tile(
        train_filepath, lidar_gdf, 'data/raw/lidar', response_dir=response_dir)
    response_filepaths.append(response_filepath)
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-c2ec68c39ac1> in <module>
      9 for train_filepath in train_filepaths:
     10     response_filepath = make_response_tiles.make_response_tile(
---> 11         train_filepath, lidar_gdf, 'data/raw/lidar', response_dir=response_dir)
     12     response_filepaths.append(response_filepath)

~/detectree/src/make_response_tiles.py in make_response_tile(tile_filepath, lidar_gdf, raw_dir, response_dir, output_dtype, output_tree_val, output_nodata, high_veg_val, logger)
     57             dfs.append(
     58                 get_from_cache_or_download(lidar_tile_filename, raw_dir,
---> 59                                            bounds))
     60         df = pd.concat(dfs)
     61         gser = gpd.GeoSeries(

~/detectree/src/make_response_tiles.py in get_from_cache_or_download(lidar_tile_filename, cache_dir, bounds, logger)
     29         request.urlretrieve(lidar_uri, local_tile_filepath)
     30 
---> 31     with lp.file.File(local_tile_filepath) as src:
     32         c = src.get_classification()
     33         # the correction is needed probably because of float point encoding

~/anaconda3/envs/python3/lib/python3.7/site-packages/laspy/file.py in __init__(self, filename, header, vlrs, mode, in_srs, out_srs, evlrs)
     62         self.in_srs = in_srs
     63         self.out_srs = out_srs
---> 64         self.open()
     65 
     66     def open(self):

~/anaconda3/envs/python3/lib/python3.7/site-packages/laspy/file.py in open(self)
     73             ## Make sure we have a header
     74             if self._header is None:
---> 75                 self._reader = base.Reader(self.filename, mode=self._mode)
     76                 self._header = self._reader.get_header()
     77             else:

~/anaconda3/envs/python3/lib/python3.7/site-packages/laspy/base.py in __init__(self, filename, mode, header, vlrs, evlrs)
    271         self.padded = False
    272         if self.mode in ("r", "r-"):
--> 273             self.setup_read_write(vlrs,evlrs, read_only=True)
    274             return
    275         elif self.mode == "rw":

~/anaconda3/envs/python3/lib/python3.7/site-packages/laspy/base.py in setup_read_write(self, vlrs, evlrs, read_only)
    319             self.evlrs = []
    320             return
--> 321         self.data_provider.point_map()
    322         if self.header.version in ("1.3", "1.4"):
    323             #gives key error if called with buffer hack for some reason...

~/anaconda3/envs/python3/lib/python3.7/site-packages/laspy/base.py in point_map(self)
    161         if self.manager.header.version not in ("1.3", "1.4"):
    162             self._pmap = np.frombuffer(self._mmap, self.pointfmt,
--> 163                                        offset=self.manager.header.data_offset)
    164             if self.manager.header.point_records_count != len(self._pmap):
    165                 if self.manager.mode == "r":

TypeError: a bytes-like object is required, not 'FakeMmap'

**Comment by martibosch** [comment]
Hello!

I myself have also come across certain issues with `.laz` files and Python, however I could overcome them by installing the `laspy`, `lastools` and `laszip` packages from conda-forge. I suggest that you try to do the following:

1. Create a dedicated conda environment named "detectree" to run the example notebooks. To that end, use the [`environment.yml`](https://github.com/martibosch/detectree-example/blob/master/environment.yml) provided in the example repository as in:

```bash
$ conda env create -n detectree -f environment.yml
```

2. Activate the environment:

```bash
$ conda activate detectree
```

3. Install the Jupyter `notebook`  package inside the new environment - note the `(detectree)` prefix in the shell:

```bash
$ (detectree) conda install -c conda-forge notebook
```

4. Launch a juptyer server from the activated environment:

```bash
$ (detectree) jupyter-notebook
```

The notebooks should then work properly.
If the above doesn't work for you, I would be happy to assist you in finding another solution :)

Best,
Martí
