### ISSUE TITLE
which python version should I use

### ISSUE THREAD

**Issue by ligaofeng0901** [martibosch/detectree#11]
* detectree version: 0.4.1
* Python version: 3.9
* Operating system:  macOS big sur 11.4 

### Description

After installing detectree, I try to execute some cli commands, like `detectree train-test-split --img-dir=./tif`,  some errors occur. 
First, `gaussian_filter1d` in `scipy.ndimage.filters` can't be found. Then, antoher error message is `ValueError: n_components=12 must be between 0 and min(n_samples, n_features)=1 with svd_solver='full'`. Anyway, it's not running correctly.

### What I Did

```
I think maybe it's cased by the wrong version of python or any dependencies. so I want to know whether should I change another python version.
```

**Comment by 37310N** [comment]
> First, `gaussian_filter1d` in `scipy.ndimage.filters` can't be found.

Hej @ligaofeng0901 the first issue can be solved following the advice in Issue #12
