### ISSUE TITLE
` _gaussian_kernel1d` cannot be imported

### ISSUE THREAD

**Issue by jehontan** [martibosch/detectree#12]
* detectree version: 0.4.1
* Python version: 3.9
* Operating system: Ubuntu 20.04

### Description

Attempt to import `detectree`, results in import error, ` _gaussian_kernel1d` cannot be imported.

This is resolved by downgrading to scipy version 1.7.0. It appears that the function has been removed in later versions of scipy.

Names prepended with '`_`' are used to indicate private functionality that is not part of the public API and should generally be avoided.

**Comment by MaxJarofka** [comment]
Hi @jehontan,
I also realized that problem and already commented on a related issue: https://github.com/martibosch/detectree-example/issues/8#issuecomment-1227155934

To solve the problem the line 
`From from scipy.ndimage.filters import _gaussian_kernel1d`
could be changed to 
`To from scipy.ndimage._filters import _gaussian_kernel1d`

I will setup a pull request to implement the corresponding changes.
Best regards

**Comment by jehontan** [comment]
Hi @MaxJarofka,

While the fix works, it's not great, as it continues to rely on functionality that's not part of the Scipy public API. Perhaps an implementation of the gaussian kernel should be added to this repository and used instead. The [actual Scipy implementation](https://github.com/scipy/scipy/blob/main/scipy/ndimage/_filters.py#L180-L208) could even be copied, as it does not rely on other hidden Scipy functionality.
