### ISSUE TITLE
[Joss review] Cite related work/comparison to other methods

### ISSUE THREAD

**Issue by rmsare** [martibosch/detectree#5]
- [x] Add one or two sentences citing related work 
- [x] Have you compared detectree to other methods? If so, it would be nice to discuss some of the pros/cons in the paper. 

Related to this, the paper documents the issues surrounding lidar-based canopy height classifiers quite well. 

- [x] Add citation section to decetree's README from [lausanne-tree-canopy](https://github.com/martibosch/lausanne-tree-canopy)

I like your suggested citation of both papers in the Lausanne project docs, and it would be good to add to the detectree docs.

[JOSS review](https://github.com/openjournals/joss-reviews/issues/2172)

**Comment by martibosch** [comment]
I have added a paragraph about related work and a note regarding the classification accuracy comparison (which we do not have because the related works report their accuracy in terms of single-tree detection i.e., segmentation).

The README now shows the suggested citation of both papers.

**Comment by rmsare** [comment]
The paper now discusses other work in detail
