### ISSUE TITLE
confusing comment in Gaussian 1D kernel creation 

### ISSUE THREAD

**Issue by easz** [martibosch/detectree#9]
https://github.com/martibosch/detectree/blob/56e8f3046ccbdbff4626ac35af99798fe78b5830/detectree/filters.py#L15

    # # Since we are calling correlate, not convolve, revert the kernel
    # weights = _gaussian_kernel1d(sigma, order, lw)[::-1]
    weights = _gaussian_kernel1d(sigma, order, lw)

the kernel is not reverted or do I understand wrong?

**Comment by martibosch** [comment]
Hello @easz,

this was written a while ago and I do not remember exactly the details, but the kernel is not reverted (the `[::-1]` is not in the uncommented line), and [it is actually `ndi.convolve`](https://github.com/martibosch/detectree/blob/main/detectree/pixel_features.py#L193) that is used to build the pixel features with the kernel.

Hope this helps. Best,
Martí
